apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercontagem
spec:
  selector:
    matchLabels:
      app: workercontagem
  replicas: 1
  template:
    metadata:
      labels:
        app: workercontagem
    spec:
      containers:
      - name: workercontagem
        image: renatogroffe/workercontagem-dotnet7-servicebus-topic-sql-appinsights
        env:
        - name: AzureServiceBus__Topic
          value: topic-contagem
        - name: AzureServiceBus__Subscription
          value: workercontagem
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionApplicationInsights
        - name: ConnectionStrings__AzureServiceBus
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionAzureServiceBus
        - name: ConnectionStrings__BaseContagem
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionSqlServer